/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSidRouteImport } from './routes/s.$sid'
import { Route as CCidRouteImport } from './routes/c.$cid'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSidRoute = SSidRouteImport.update({
  id: '/s/$sid',
  path: '/s/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const CCidRoute = CCidRouteImport.update({
  id: '/c/$cid',
  path: '/c/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/goals': typeof GoalsRoute
  '/mistakes': typeof MistakesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/c/$cid': typeof CCidRoute
  '/s/$sid': typeof SSidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/goals': typeof GoalsRoute
  '/mistakes': typeof MistakesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/c/$cid': typeof CCidRoute
  '/s/$sid': typeof SSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/goals': typeof GoalsRoute
  '/mistakes': typeof MistakesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/c/$cid': typeof CCidRoute
  '/s/$sid': typeof SSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/goals'
    | '/mistakes'
    | '/revision'
    | '/settings'
    | '/c/$cid'
    | '/s/$sid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/goals'
    | '/mistakes'
    | '/revision'
    | '/settings'
    | '/c/$cid'
    | '/s/$sid'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/goals'
    | '/mistakes'
    | '/revision'
    | '/settings'
    | '/c/$cid'
    | '/s/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  GoalsRoute: typeof GoalsRoute
  MistakesRoute: typeof MistakesRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  CCidRoute: typeof CCidRoute
  SSidRoute: typeof SSidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sid': {
      id: '/s/$sid'
      path: '/s/$sid'
      fullPath: '/s/$sid'
      preLoaderRoute: typeof SSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$cid': {
      id: '/c/$cid'
      path: '/c/$cid'
      fullPath: '/c/$cid'
      preLoaderRoute: typeof CCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  GoalsRoute: GoalsRoute,
  MistakesRoute: MistakesRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  CCidRoute: CCidRoute,
  SSidRoute: SSidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
